[tool.ruff]
fix = true
select = ["E", "F", "W", "I", "RUF"]
ignore = ["E501"] # line too long | Black take care of it

[tool.ruff.flake8-quotes]
docstring-quotes = "double"

[tool.doc8]
ignore = ["D001"] # we follow a 1 line = 1 paragraph style
ignore-path = ["docs/source/modules/*"]

[tool.codespell]
skip = 'docs/source/_data/modules/*.json,*.po,docs/source/modules/dwn/*,docs/build/*,docs/source/_bib/workflows/drivers.bib,docs/source/_data/*'
ignore-words-list='alos,cywgin,toi,aoi,bui,BUI'