name: Build

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with: 
          ref: ${{ github.head_ref }}

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: pip install sphinx sphinx-intl

      - name: generate .po files
        run: |
          sphinx-build -b gettext docs/source docs/build/gettext
          sphinx-intl update -p docs/build/gettext --locale-dir docs/source/_locale -l fr -l en -l es

      - name: push the files
        uses: stefanzweifel/git-auto-commit-action@v4
        with: 
          commit_message: Automatic translation update
